[build]
command = "./cloudflare-build.sh"
output_directory = "out"
base_directory = ""

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"

[site]
bucket = "./out"
entry-point = "."

[env.production]
name = "production"
route = "*"

[env.staging]
name = "staging"
route = "staging.*"
